# Arithmetic with Numpy Arrays
Arrays are important because they enable you to express batch operations on data without writing any for loops.

In [2]:
# imports
import numpy as np

In [3]:
arr = np.array([[1., 2., 3. ],[4., 5., 6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
# multiplication
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
# subtraction
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# addition
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [7]:
# division
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

## with scalars
array operation with scalars propagate the scalar argument to each element in the array.

In [8]:
# 1 over the array
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [9]:
# raising to a power
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [11]:
# lets define another array
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [17]:
# comparing two arrays
res = arr > arr2
print("type of res = {}".format(res.dtype))
res

type of res = bool


array([[ True, False,  True],
       [False,  True, False]])

### hehe this concludes arithmetic with numpy

# Basic Indexing and Slicing
There are many various ways we may want to select an item or group of items from an array. Numpy offers many such methods.

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# selecting item at index=5
arr[5]

5

In [22]:
# selecting the sublist of items from 5 to 8 exclusive
arr[5:8]

array([5, 6, 7])

In [25]:
# reassigning a sublist of items to a particular value
arr[5:8] = 13
arr

array([ 0,  1,  2,  3,  4, 13, 13, 13,  8,  9])

In [31]:
# reassigning a sublist of items to a another list
## note that the sublist and list must be of the same length
arr[5:8] = [n for n in range(14,17)]
arr

array([ 0,  1,  2,  3,  4, 14, 15, 16,  8,  9])

In [34]:
# lets look at this example to understand referencing
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice = [n for n in range(20,23)]
arr_slice[1] = 21421424 
print("arr_slice = \n {}".format(arr_slice))
print("arr = \n{}".format(arr))

arr_slice = 
 [20, 21421424, 22]
arr = 
[0 1 2 3 4 5 6 7 8 9]
