# Universal Functions: Fast Element-wise Array Functions
A universal function is one that performs element-wise operations on data in ndarrays.

In [2]:
# imports 
import numpy as np

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# example 1: sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
# example 2: exp
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

The ones above are known as unary functions.
The following such as add or maximum take two arrays and return a single array as the result: binary ufuncs

In [9]:
x = np.random.randn(8)
y = np.random.randn(8)
print("x:\n{}\n\ny:\n{}\n".format(x,y))

x:
[ 1.55489378 -0.58704986  1.38410597 -0.97308183 -1.14016687  0.02639519
  0.2637115   0.34623479]

y:
[-0.04220487  0.44627562  0.36948491 -0.62368366  1.18075065  0.93116763
  1.49635429  0.4992786 ]



In [10]:
# example 3: maximum
np.maximum(x,y)

array([ 1.55489378,  0.44627562,  1.38410597, -0.62368366,  1.18075065,
        0.93116763,  1.49635429,  0.4992786 ])

In [16]:
# not common tho, ufunc can return multiple arrays
arr = np.random.randn(7) * 5
print("arr:\n{}\n".format(arr))
remainder, whole_part = np.modf(arr)
print("remainder:\n{}\n\nwhole_part:\n{}\n".format(remainder,whole_part))

arr:
[ 4.29018808 -6.95449368 -4.30458731 -1.48980917  5.17254808  5.37793321
 -0.28370014]

remainder:
[ 0.29018808 -0.95449368 -0.30458731 -0.48980917  0.17254808  0.37793321
 -0.28370014]

whole_part:
[ 4. -6. -4. -1.  5.  5. -0.]

