# Installation
conda install numpy  
pip install numpy  

## Ndarray
The basis of numpy is the ndarray. The number of dimensions defined by it is given by its **shape** attr.

In [50]:
# imports
import numpy as np
import random

In [6]:
# to define an ndarray, we use the numpy array() function and pass a list as param
a = np.array([1,2,3])
print(a)

# to get the type, use type() function
print(type(a))

# to get the dtype associated with the array, use dtype attr
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


In [11]:
# for dimensions
print(a.ndim)
# for size
print(a.size)
# for shape
print(a.shape)

1
3
(3,)


In [15]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype) # dtype
print(b.size)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int64
6
(2, 3)


In [19]:
# an ndarray can also be created with tuples
at = np.array((1,2,3))
print(at)
bt = np.array(((1,2,3),(4,5,6)))
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


ndarray can store a wide variety of data types refer 

In [25]:
# the dtype option can be used to define what data type the ndarray can store.
f = np.array([[1,4,7],[5,2,7]], dtype=complex)
print(f)

[[1.+0.j 4.+0.j 7.+0.j]
 [5.+0.j 2.+0.j 7.+0.j]]


In [62]:
# intrinsic array creation
## using the zeros function, we can create an array of zeros only
zeros_arr = np.zeros((3,2), dtype=int)
print(zeros_arr)
## same thing can be done with ones()
ones_arr = np.ones((3,2))
print(ones_arr)

## can be done too with arange()
### with a defined range
arange_arr = np.arange(0,20)
print(arange_arr)

### with a defined range and increments
arange_arr2 = np.arange(0,20,5)
print(arange_arr2)

### another function very similar to arange is linspace
## does the same as arange(i,j,n) but n defines the number of values to split
lin_arr = np.linspace(0,20,5)
print(lin_arr)

## using random 
rand_arr = np.random.random(3)
print(rand_arr)
rand_arr2 = np.random.random((3,2))
print(rand_arr2)

[[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15]
[ 0.  5. 10. 15. 20.]
[0.47185877 0.4332968  0.68366104]
[[0.7361834  0.9165775 ]
 [0.71351897 0.4549296 ]
 [0.70637866 0.28187494]]


## Basic Operations
Let us see some basic ops on numpy arrays  

In [77]:
# Arithmetic Operators
## define vars
a = np.arange(3,7)
b = np.arange(10,14)

print("Addition: {}".format(a+b))
print("Subtraction: {}".format(a-b))
print("Multiplication: {}".format(a*b))
print("Divison: " + str(a/b))

Addition: [13 15 17 19]
Subtraction: [-7 -7 -7 -7]
Multiplication: [30 44 60 78]
Divison: [0.3        0.36363636 0.41666667 0.46153846]


In [88]:
# reshaping an np array. can only be done if len(arr)==i*j
exmp = np.arange(12)
exmp.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
# The matrix product
A = np.arange(18, 27).reshape(3,3)
B = np.arange(9).reshape(3,3)
print(np.dot(A,B))

[[177 234 291]
 [204 270 336]
 [231 306 381]]


array([[ 69,  72,  75],
       [258, 270, 282],
       [447, 468, 489]])

In [102]:
# Increment operator
exmp = np.arange(4)
print("original: \n{}".format(exmp))
print("increment: \n{}".format(exmp+1))
print("decrement: \n{}".format(exmp-1))
exmp1 = exmp
exmp1 += 4
print("increment 4: \n{}".format(exmp1))
exmp1 -= 3
print("decrement 3: \n{}".format(exmp1))

original: 
[0 1 2 3]
increment: 
[1 2 3 4]
decrement: 
[-1  0  1  2]
increment 4: 
[4 5 6 7]
decrement 3: 
[1 2 3 4]


Slicing, indexing and iterating are the same as ordinary lists

In [107]:
# Conditions and Boolean arrays
A = np.random.random((5,5))
print("original: \n{}".format(A))
print("\ngreater than 0.5: \n{}".format(A > 0.5))
print("\nless than 0.5: \n{}".format(A < 0.5))

original: 
[[0.75782216 0.87604487 0.60761762 0.32797789 0.47081979]
 [0.78733227 0.20721807 0.39619693 0.26874802 0.00460407]
 [0.11040154 0.49404177 0.19997387 0.67309831 0.42748253]
 [0.40609768 0.09680058 0.06312209 0.99842975 0.1455549 ]
 [0.0510288  0.53305474 0.25938281 0.18331373 0.85794703]]

greater than 0.5: 
[[ True  True  True False False]
 [ True False False False False]
 [False False False  True False]
 [False False False  True False]
 [False  True False False  True]]

less than 0.5: 
[[False False False  True  True]
 [False  True  True  True  True]
 [ True  True  True False  True]
 [ True  True  True False  True]
 [ True False  True  True False]]


## Array manipulation
Joining and Splitting arrays

In [120]:
# joining arrays
## def vars
A = np.arange(16).reshape(4,4)
B = np.arange(4,20).reshape(4,4)

## using vstack to joing vertically
arr_vstack = np.vstack((A,B))
print("Vertical stack: \n{}".format(arr_vstack))

## using hstack to join horizontally
arr_hstack = np.hstack((A,B))
print("\nHorizontal stack: \n{}".format(arr_hstack))

## using column and row stack
a = np.array([1,2,3,4])
b = np.array([9,8,6,5])
c = np.array([9,4,7,3])
print("\n\nColumn stack: \n{}".
      format(np.column_stack((a,b,c))))
print("\nRow stack: \n{}".
     format(np.row_stack((a,b,c))))

Vertical stack: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Horizontal stack: 
[[ 0  1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10 11]
 [ 8  9 10 11 12 13 14 15]
 [12 13 14 15 16 17 18 19]]


Column stack: 
[[1 9 9]
 [2 8 4]
 [3 6 7]
 [4 5 3]]

Row stack: 
[[1 2 3 4]
 [9 8 6 5]
 [9 4 7 3]]


In [130]:
# splitting arrays
## def vars
A = np.arange(16).reshape(4,4)
B = np.arange(4,20).reshape(4,4)

# splitting using hsplit
print("Original A: \n{}".format(A))
A_hsplit2 = np.hsplit(A,2)
print("Split A to 2: \n{}".format(A_hsplit2))
print("Split A to 4: \n{}".format(np.hsplit(A,4)))
## vsplit does the same in the vertical direction

Original A: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Split A to 2: 
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Split A to 4: 
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
