# Installation
pip install pandas  
and other methods

In [1]:
# imports 
import pandas as pd
import numpy as np

## The Series data structure

In [2]:
# declaring a series
s = pd.Series([12,-4,7,9])
print("original series:\n{}".format(s))

original series:
0    12
1    -4
2     7
3     9
dtype: int64


In [3]:
# declaring with defined index
kanye_info = pd.Series(
    [20, 6, 200, 2],
    index=['age', 'height', 'level', 'year']
)
kanye_info.index # to get an nparray of the indices
kanye_info.values # to get an nparray of the values

array([ 20,   6, 200,   2])

In [4]:
# getting values using index
print("Kanye age = {}".format(kanye_info['age']))

# setting values using index
kanye_info['height'] = 5
print("Kanye new age: {}".format(kanye_info['height']))

Kanye age = 20
Kanye new age: 5


In [5]:
# defining series from numpy arrays
np_arr = np.array([1,2,3,4])
exmp_s = pd.Series(np_arr)
print("Result example: \n{}".format(exmp_s))

Result example: 
0    1
1    2
2    3
3    4
dtype: int64


### NOTE
operations and mathematical functions that work on numpy arrays are applicable on series as well.

## DataFrame structure

In [11]:
# defining a dataframe
## the most common method is to pass a dict object to the DataFrame constructor
data = {
    'color':['blue','green','yellow','red','white'],
    'object': ['ball','pen','pencil','paper','mug'],
    'price': [1.2,1.0,0.6,0.9,1.7]
}
d_frame = pd.DataFrame(data)

blue


In [17]:
# if the data from which we want to make the dataframe contains more columns than necessary, we specify
d_frame2 = pd.DataFrame(data, columns=['object', 'price'])
print("d_frame2: \n{}".format(d_frame2))

# we can also specify the value of the indices
d_frame3 = pd.DataFrame(data, index=['one','two','three','four','five'])
print("\nd_frame3: \n{}".format(d_frame3))

d_frame2: 
   object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

d_frame3: 
        color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7


In [23]:
# a dataframe can also be defined using an array object
d_frame4 = pd.DataFrame(
    np.arange(25).reshape((5,5)),
    index=[1,2,3,4,5],
    columns=['one','two','three','four','five']
)
print("d_frame4: \n{}".format(d_frame4))

d_frame4: 
   one  two  three  four  five
1    0    1      2     3     4
2    5    6      7     8     9
3   10   11     12    13    14
4   15   16     17    18    19
5   20   21     22    23    24


In [34]:
# selecting elements
## getting all the columns
exmp = pd.DataFrame(
    np.arange(25).reshape((5,5)),
    index=[1,2,3,4,5],
    columns=['one','two','three','four','five']
)
exmp_cols = exmp.columns
print("exmp columns: {} \n".format(exmp_cols))

## getting all values
exmp_vals = exmp.values
print("exmp values: \n{} \n".format(exmp_vals))

## getting a column
exmp_col1 = exmp['one']
print("exmp column 1:\n{}\n".format(exmp_col1))

## getting an index
exmp_idx1 = exmp.index[1]
print("exmp index 1: {}\n".format(exmp_idx1))

# setting values is the other way around

exmp columns: Index(['one', 'two', 'three', 'four', 'five'], dtype='object') 

exmp values: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

exmp column 1:
1     0
2     5
3    10
4    15
5    20
Name: one, dtype: int64

exmp index 1: 2

