# Linear Algebra
We look at some implementation of linear algebra in numpy built from math and in contrast with some operation in MATLAB.

In [1]:
# imports 
import numpy as np

In [4]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
print("x:\n{}\ny:\n{}\n".format(x,y))

x:
[[1 2 3]
 [4 5 6]]
y:
[[ 6 23]
 [-1  7]
 [ 8  9]]



calculating the dot product from x

In [8]:
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [9]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [10]:
# as seen, the two above are the same

calculating the dot product from x

In [11]:
y.dot(x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [12]:
np.dot(y,x)

array([[ 98, 127, 156],
       [ 27,  33,  39],
       [ 44,  61,  78]])

In [13]:
# you wise where I am going with this

In [20]:
# the symbol also works on an infix operator that performs matrix multiplication
x @ np.ones(3)

array([ 6., 15.])

## Someting of Interest: linalg
numpy.linalg has a standard set of matrix decompositions and things like inverse
and determinant. These are implemented under the hood via the same industry-
standard linear algebra libraries used in other languages like MATLAB and R, such as
BLAS, LAPACK, or possibly (depending on your NumPy build) the proprietary Intel
MKL (Math Kernel Library):